use_frameworks!

target 'Example' do
  pod 'SwiftyJSON', :tag => '3.1.4', :git => 'https://github.com/SwiftyJSON/SwiftyJSON'
  pod 'Charts', :tag => 'v3.0.3', :git => 'https://github.com/danielgindi/Charts.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

